services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - app-volume:/var/www/html
      - ./app:/var/www/html
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - app-volume:/var/www/html/
      - ./app:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  app-volume:
    external: true